language: node_js

node_js:
  - "8"
  - "9"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:  
  - npm install -g codecov
  - yarn install

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
- yarn jest --coverage
- codecov